InternBoard/InternBoard/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views as auth_views



urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')), # a build in feature from django
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('jobsApp.urls', namespace='jobs')),
    path('boards/', include('boards.urls', namespace='boards')),
    path('blog/', include('blog.urls', namespace='blog')),
    
]

InternBoard/accounts/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views



# from accounts import views as accounts_views
# from . import views
app_name='accounts'

urlpatterns = [
    # url(r'^$', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('profile/',views.profile , name='profile'),
    path('profile/edit',views.profile_edit , name='profile_edit'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='password/password_reset.html',
        email_template_name='password/password_reset_email.html',
        subject_template_name='password/password_reset_subject.txt'
    ), name='password_reset'),
    path('reset/finish/', auth_views.PasswordResetDoneView.as_view(
        template_name='password/password_reset_finish.html'), name='password_reset_finish'),
    path('reset/confirm/<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirming.html'),
        name='password_reset_confirming'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password/password_change.html'),
    name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password/password_change_done.html'),
    name='password_change_done'),
    path('settings/account/', accounts_views.UserUpdateView.as_view(), name='myaccount'),

    
]

# app_name='job'

# urlpatterns = [
#     path('signup/',views.signup , name='signup'),
#     path('profile/',views.profile , name='profile'),
#     path('profile/edit',views.profile_edit , name='profile_edit'),
# ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InternBoard/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('postlistblog/', views.PostList.as_view(), name='post_list_blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail_blog'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

InternBoard/jobsApp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'jobsApp'

urlpatterns = [
    path('', views.joblist, name="job-list"), # reverse("jobs:job_list")
    path('job-detail/<str:slug>', views.job_detail, name="job-detail"),
    path('add-job', views.add_job, name="add-job"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InternBoard/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

# django signals
from django.db.models.signals import post_save 
from django.dispatch import receiver

# Create your models here.
# because django already includes user table in the database i have 2 choices to create a user 1. abstract a new user 2. extend from the existing one
class Profile(models.Model):
    # Relation One to One
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    city = models.ForeignKey('City', related_name='user_city', on_delete=models.CASCADE , blank=True, null=True)
    phone_number = models.CharField(max_length=15)
    image  = models.ImageField(upload_to='profile/')

    class Meta:
        verbose_name = _("profile")
        verbose_name_plural = _("profiles")

    def __str__(self):
        return str(self.user)

class City(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = _("city")
        verbose_name_plural = _("cities")

    def __str__(self):
        return self.name
    
    
# create new user ---> create new empty profile
# using signals in django: https://docs.djangoproject.com/en/4.1/topics/signals/

# django signals code from here: https://simpleisbetterthancomplex.com/tutorial/2016/07/28/how-to-create-django-signals.html
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created: # 201
        Profile.objects.create(user=instance)

InternBoard/accounts/forms.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
# from .models import Profile


# class SignupForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username','email','password1','password2']

# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields= ['username','first_name','last_name','email'] 

# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['city','phone_number','image'].

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields= ['username','first_name','last_name','email'] 

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','phone_number','image']

InternBoard/accounts/views.py
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
# from .models import Profile, UserForm , ProfileForm

from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

# from django.shortcuts import redirect, render
# from .forms import SignupForm, UserForm, ProfileForm
# from django.contrib.auth import authenticate, login
# from django.contrib.auth import login as auth_login

# from .forms import SignUpForm

# from .models import Profile
# from django.contrib.auth.forms import UserCreationForm
# from .models import Profile, UserForm , ProfileForm

# from django.urls import reverse
# Create your views here.


# def signup(request):
#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             auth_login(request, user)
#             return redirect('/')
#     else:
#         form = SignUpForm()
#     return render(request, 'registration/signup.html', {'form': form})

# def signup(request):
#     # 1. check if the request method is post (there is data & you want to save it)
#     if request.method=="POST":
#         form = SignupForm(request.POST)
        
#         # 2. check if the data is valid the save it 
#         if form.is_valid():
#             form.save()
            
#             # 3. to update the session i need to get the username & the password data
#             username = form.cleaned_data['username']  # will give me the username
#             password = form.cleaned_data['password1'] # will give me the password 1 or 2 are the same so it doesn't matter which one i chose
            
#             # 4. make sure that the data i took exist
#             user = authenticate(username=username,password=password) #TRUE/FALSE
            
#             # 5. if its correct then i need to login
#             login(request,user)
            
#             # 6. redirect the user to there profile
#             return redirect('/')
    
#     # 7. check if the user didn't put any data yet the render the form
#     else:
#         form = SignupForm()
        
#     # 8. render the html page
#     return render(request,'registration/signup.html',{'form':form})


# '''
# 1. It retrieves the Profile object for the current user by calling the get method on the Profile model's objects attribute and passing it the user field of the request object.
# 2. It renders the profile.html template and passes the Profile object as the profile variable to the template.
# '''


def profile(request):
    profile = Profile.objects.get(user=request.user) #OOP
    return render(request,'accounts/profile.html',{'profile': profile})


# PUT & PATCH
def profile_edit(request):
    # get from the database
    profile = Profile.objects.get(user=request.user)

    # Save the form
    if request.method=='POST':
        userform = UserForm(request.POST,instance=request.user)
        profileform = ProfileForm(request.POST, request.FILES,instance=profile ) # request.files to be able to update the image
        
        # check on validation for the 2 forms
        #        T                      T
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile = profileform.save(commit=False) # i didn't save because i need first to send it to the user 
            myprofile.user = request.user # send data to the user then save
            myprofile.save() 
            
            # redirect to the accounts/profile
            return redirect(reverse('accounts:profile'))
    
    # Show the forms userform & profileform
    else :
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)

    return render(request,'accounts/profile_edit.html',{'userform':userform , 'profileform':profileform})

@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email', )
    template_name = 'myaccount.html'
    success_url = reverse_lazy('myaccount')

    def get_object(self):
        return self.request.user

InternBoard/accounts/templates/password/password_change.html
{% extends 'base_accounts.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <h4>Change password</h4>
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-primary">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

InternBoard/accounts/templates/password/password_change_done.html
{% extends 'base_accounts.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'jobs:job-list' %}" class="btn btn-primary">Return to home page</a>
{% endblock %}

InternBoard/accounts/templates/password/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to your email to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Enter email to reset password</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

InternBoard/accounts/templates/password/password_reset_complete.html
{% extends 'base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title" >Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'login' %}" class="btn btn-primary btn-block">Return to login</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

InternBoard/accounts/templates/password/password_reset_confirming.html
{% extends 'base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-primary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

InternBoard/accounts/templates/password/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirming' uidb64=uid token=token %}

In case you forgot your InternLikeAPro username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The InternLikeAPro Team

InternBoard/accounts/templates/password/password_reset_finish.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'login' %}" class="btn btn-primary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}