InternBoard/InternBoard/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views as auth_views



urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')), # a build in feature from django
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('jobsApp.urls', namespace='jobs')),
    path('boards/', include('boards.urls', namespace='boards')),
    path('blog/', include('blog.urls', namespace='blog')),
    
]

InternBoard/accounts/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views



# from accounts import views as accounts_views
# from . import views
app_name='accounts'

urlpatterns = [
    # url(r'^$', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('profile/',views.profile , name='profile'),
    path('profile/edit',views.profile_edit , name='profile_edit'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='password/password_reset.html',
        email_template_name='password/password_reset_email.html',
        subject_template_name='password/password_reset_subject.txt'
    ), name='password_reset'),
    path('reset/finish/', auth_views.PasswordResetDoneView.as_view(
        template_name='password/password_reset_finish.html'), name='password_reset_finish'),
    path('reset/confirm/<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirming.html'),
        name='password_reset_confirming'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password/password_change.html'),
    name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password/password_change_done.html'),
    name='password_change_done'),
    path('settings/account/', accounts_views.UserUpdateView.as_view(), name='myaccount'),

    
]

# app_name='job'

# urlpatterns = [
#     path('signup/',views.signup , name='signup'),
#     path('profile/',views.profile , name='profile'),
#     path('profile/edit',views.profile_edit , name='profile_edit'),
# ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InternBoard/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('postlistblog/', views.PostList.as_view(), name='post_list_blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail_blog'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

InternBoard/boards/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from boards import views


app_name = 'boards'

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.ForumListView.as_view(), name='home'),
    # path('boards/<int:pk>/', views.board_topics, name='board_topics'),
    path('boards/<int:pk>/', views.TopicListView.as_view(), name='board_topics'),
    path('boards/<int:pk>/new/', views.new_topic, name='new_topic'),
    # path('boards/<int:pk>/topics/<int:topic_pk>/', views.topic_posts, name='topic_posts'),
    path('boards/<int:pk>/topics/<int:topic_pk>/', views.PostListView.as_view(), name='topic_posts'),
    path('boards/<int:pk>/topics/<int:topic_pk>/reply/', views.reply_topic, name='reply_topic'),
    path('boards/<int:pk>/topics/<int:topic_pk>/posts/<int:post_pk>/edit/',
        views.PostUpdateView.as_view(), name='edit_post'),



]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InternBoard/jobsApp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'jobsApp'

urlpatterns = [
    path('', views.joblist, name="job-list"), # reverse("jobs:job_list")
    path('job-detail/<str:slug>', views.job_detail, name="job-detail"),
    path('add-job', views.add_job, name="add-job"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InternBoard/jobsApp/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User


JOB_TYPE = (
    ('Six Months','Six Months'),
    ('Three Months','Three Months'),
    )

def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "jobs/%s.%s"%(instance.id,extension)

# Job table/Entity
#https://docs.djangoproject.com/en/4.1/ref/models/fields/
class Job(models.Model):  
    title        = models.CharField(max_length=100)  
    job_type     = models.CharField(max_length=15 , choices=JOB_TYPE)
    description  = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy      = models.IntegerField(default=1)
    salary       = models.IntegerField(default=0)
    experience   = models.IntegerField(default=1) 
    image = models.ImageField(upload_to= image_upload)
    
    # https://docs.djangoproject.com/en/4.1/ref/forms/fields/ 
    # short label for something, containing only letters, numbers, underscores or hyphens. They’re generally used in URLs.
    slug = models.SlugField(blank=True, null=True) # https://www.jobboard.com/add-the-slug-field-inside-django-model/
    
    # Relations
    category     = models.ForeignKey('Category', on_delete=models.CASCADE, default=1) # one to many
    owner = models.ForeignKey(User, related_name='job_owner', on_delete=models.CASCADE)
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.title) # slugify will take the title and replace the space with underscore (job-board-software-engineer)
        super(Job,self).save(*args, **kwargs)
        
        
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-published_at']
        db_table = 'jobs_table'
    
class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'category_table'

# Apply form   
class Apply(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=100000)
    created_at = models.DateTimeField(auto_now=True)

    # Relations
    job = models.ForeignKey(Job, related_name='apply_job', on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "applications_table"

InternBoard/jobsApp/forms.py
from django import forms
from .models import Apply , Job


class ApplyForm(forms.ModelForm):
    class Meta:
        model = Apply
        fields = ['name' ,'email','website','cv','cover_letter']


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
        exclude = ('owner','slug')

InternBoard/jobsApp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Job
from .forms import JobForm, ApplyForm
from django.contrib.auth.decorators import login_required
from .filter import JobFilter
from django.core.paginator import Paginator

def joblist(request):
    jobs = Job.objects.all()

    #myfilter
    myfilter = JobFilter(request.GET, queryset=jobs)
    jobs = myfilter.qs # qs == queryset

    #pagenation
    paginator = Paginator(jobs, 5) # Show 3 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        "jobs": page_obj, 
        "myfilter": myfilter
    }
    return render(request, "joblist.html", context)
    
@login_required
def job_detail(request, slug):
    job_detail = Job.objects.get(slug=slug) # will retrieve on job
    # job_detail = Job.object.filter() # will retrieve on job from a list according to some filtration

    # Django bootstrap:  https://django-bootstrap4.readthedocs.io/en/latest/quickstart.html
    if request.method=='POST':
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
                    myform = form.save(commit=False)
                    myform.job = job_detail
                    myform.save()
                    print('Posted Successfully')

    else:
        form = ApplyForm()


    context = {
         'job' : job_detail ,
           'form' : form
           }
    return render(request,'jobdetail.html', context)

@login_required
def add_job(request):
    if request.method=='POST':
        pass
        form = JobForm(request.POST , request.FILES) # request.FILES if theres any pic <form method="POST" enctype="multipart/form-data">
        if form.is_valid(): # to make sure the form is valid
            myform = form.save(commit=False) # save the form but not in the db because i need to add the person who added the job
            myform.owner = request.user
            myform.save()
            return redirect(reverse('jobs:job-list')) # after saving redirect to the job list REVERSE takes the urls (project:app)

    else:
        form = JobForm()
    return render(request,'addjob.html', {'form': form})

InternBoard/jobsApp/templates/__footer.html
{% load static %}
<footer class="footer">
    <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                        <div class="footer_title">
                            <h3 class="footer_title">
                                Address & Social links
                            </h3>
                        </div>
                        <p>
                            internlikeapro@support.com <br>
                            +254740298531<br>
                            Nairobi, Kenya
                        </p>
                        <div class="socail_links">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-xl-2 col-md-6 col-lg-2">
                    <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                        <h3 class="footer_title">
                            Company
                        </h3>
                        <ul>
                            <li><a href="#">About Us </a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#"> Pricing</a></li>
                            <li><a href="#">Carrier Tips</a></li>
                            <li><a href="#">FAQ</a></li>
                        </ul>

                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                        <h3 class="footer_title">
                            Category
                        </h3>
                        <ul>
                            <li><a href="#">Design & Art</a></li>
                            <li><a href="#">Engineering</a></li>
                            <li><a href="#">Sales & Marketing</a></li>
                            <li><a href="#">Finance</a></li>
                            <li><a href="#">Community Services</a></li>

                        </ul>
                    </div>
                </div>
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                        <h3 class="footer_title">
                            Subscribe
                        </h3>
                        <form action="#" class="newsletter_form">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit" style="background-color:#0046d3;">Subscribe</button>
                        </form>
                        <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                            luckily.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
        <div class="container">
            <div class="footer_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved by InternLikeAPro

                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

InternBoard/jobsApp/templates/__header.html
{% load static %}
<header>
    <div class="header-area ">
        <div id="sticky-header" class="main-header-area">
            <div class="container-fluid ">
                <div class="header_bottom_border">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="./base.html">
                                    <img src="../static/img/logo.png" alt="" style="width: 50px;height: 50px;">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="/">home</a></li>
                                        <li><a href="{% url 'jobs:job-list' %}">Browse Internships</a></li>
                                        <li><a href="{% url 'blog:post_list_blog' %}">Blog</a></li>
                                        <li><a href="{% url 'boards:home' %}">Discussion Forums</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="Appointment">
                            
                                {% if request.user.is_authenticated %}

                                    <ul class="navbar-nav ml-auto">
                                      <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle m-3" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-transform: capitalize; color: white;">
                                          {{ user.username }}
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                          <a class="dropdown-item" href="#">My account</a>
                                          <a class="dropdown-item" href="#">Change password</a>
                                          <div class="dropdown-divider"></div>
                                          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                                        </div>
                                      </li>
                                    </ul>


                                {% else %}
                                <form class="form-inline ml-auto">
                                  <a href="{% url 'accounts:login' %}" class="btn bg-light btn-primary boxed-btn4">Log in</a>

                                  <a href="{% url 'accounts:signup' %}" class="btn bg-light btn-primary m-3 boxed-btn4">Sign up</a>
                                </form>
                              {% endif %}
                            
                                
                                <div class="d-none d-lg-block bg-light rounded">
                                    <a class="boxed-btn4" href="{% url 'jobs:add-job' %}">Post Internship</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</header>

InternBoard/jobsApp/templates/addjob.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="apply_job_form white-bg">
                    <h4>Post New Internship</h4>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        {% bootstrap_form form %}

                        <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

InternBoard/jobsApp/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Internship Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>


<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    {% include '__header.html'%}
    <!-- header-end -->

    
    {% block body %}
        
    {% endblock body %}
        

    <!-- footer start -->
    {% include '__footer.html' %}
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- <script src="{% static 'js/gijgo.min.js' %}"></script> -->
    <script src="{% static 'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>

InternBoard/jobsApp/templates/base_generic.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
</div>
<!--/ bradcam_area  -->
<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="apply_job_form white-bg">
                    {% block content %}
                        
                    {% endblock content %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

InternBoard/jobsApp/templates/jobdetail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="apply_job_form white-bg">
                    <h4>Post New Internship</h4>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}

                        <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

InternBoard/jobsApp/templates/joblist.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block body %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{jobs|length}}+ Internships Available</h3>

                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="job_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter options</h3>
                        <form method="GET" >
                            {% bootstrap_form myfilter.form %}
                            <input type="submit" value="Search" class="boxed-btn3 w-100 mt-2"  style="background-color:#0046d3;">
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg ">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Internship Listing</h4>
                            </div>
                            <div class="col-md-6">

                            </div>
                        </div>
                    </div>
                </div>

                <div class="job_lists m-0" style="border-color: #0046d3;">
                    <div class="row" style="border-color: #0046d3;">

                        {% for job in jobs %}
                        <div class="col-lg-12 col-md-12">
                            <div class="single_jobs white-bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div class="thumb">
                                        <!-- <img src="{% static '/jobs/None.jpg' %}" alt=""> -->
                                        <img src="{{job.image.url}}" alt="internship image">
                                    </div>
                                    <div class="jobs_conetent">
                                        <a href="{% url 'jobs:job-detail' job.slug%}">
                                            <h4>{{job}}</h4>
                                        </a>
                                        <div class="links_locat d-flex align-items-center">
                                            <div class="location">
                                                <p> <i class="fa fa-map-marker"></i>Remote</p>
                                            </div>
                                            <div class="location">
                                                <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <!-- <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a> -->
                                        <a href="{% url 'jobs:job-detail' job.slug%}" class="boxed-btn3"  style="background-color:#0046d3;">Apply Now</a>
                                    </div>
                                    <div class="date">
                                        <!-- https://docs.djangoproject.com/en/4.1/ref/templates/builtins/ -->
                                        <p>Posted on {{job.published_at|date:'d M Y'}}</p>

                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            {% if jobs.has_other_pages %}
                            <!-- https://docs.djangoproject.com/en/4.1/topics/pagination/ -->
                            <div class="pagination_wrap">
                                <ul>
                                    {% if jobs.has_previous %}
                                    <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i>
                                        </a></li>
                                    {% endif %}

                                    {% for i in jobs.paginator.page_range %}
                                    <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                    {% endfor %}

                                    {% if jobs.has_next %}
                                    <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_listing_area_end  -->
{% endblock body %}